### ISSUE TITLE
WI-1.7.1: Sign up validation

### ISSUE THREAD

**Issue by antjimort** [salmorejo-hub-1/uvlhub#50]
Description: Add a functionality by means of which a new user can be sent a confirmation email after filling the signup form to verify his/her email address

Steps to reproduce
1- The user fills the signup form
2- The user is redirected to the check-inbox page, where the user is told to check his/her mail inbox
3- The user clicks on the link sent to verify his/her email address

Expected result:
The email is correctly sent, and the verification link works properly

Current result: This is not implemented yet

Additional information (Optional): Intentionally blank

**Comment by isabelcan7** [comment]
acho escribe una descripcion en condiciones aunque sea con chatgpt xd
