### ISSUE TITLE
WI-1.6.7: Discord does not accept messages longer than 2000 characters

### ISSUE THREAD

**Issue by JosueRodLop** [salmorejo-hub-1/uvlhub#56]
Description: Discord does not support messages longer than 2000 characters so in some commands as the one that lists datasets can produce errors if too many information needs to be displayed.
Steps to reproduce:

- Activate bot, configure user token and type !datasets.

Expected result: A dynamic  view must be implemented to support longer message in a way that the user can change between pages inside the message.

Current result: Implementation of embed messages that allows to send messages longer than 2000 characters and the use of buttons to navigate thrugh pages of data.
Additional information:

- Error: discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In content: Must be 2000 or fewer in length.

**Comment by isabelcan7** [comment]
que quejica es el bot madre mía, la que está dando
