### ISSUE TITLE
WI-1.6.13: Discord bot on docker

### ISSUE THREAD

**Issue by JosueRodLop** [salmorejo-hub-1/uvlhub#65]
Description: Configure discord bot to deploy it on docker containers.

Process followed:

1.  Create Dockerfile
2. Edit Docker compose configuration file.
3. Edit discord bot code  to adapt to Docker environment.
4. Create entry script to make bot docker wait a response from database before running the bot.

Modified modules: discordbot module.

Additional information:

**Comment by JosueRodLop** [comment]
An error has been detected: it is necessary to run 2 times docker compose up -d --build in order to deploy the bot. If not done 2 times or without --build, the container will terminate with code (1) because no local variables from .env are passed to the container.

**Comment by JosueRodLop** [comment]
Error fixed: the problem was that the bot tried to access the database after the docker service started, but not before mariadb was accessible.

**Comment by isabelcan7** [comment]
Josué tu sí que sabes escribir issues, para ispp escribes tú la documentacion vale?
