### ISSUE TITLE
Fix worfklows

### ISSUE THREAD

**Issue by antjimort** [salmorejo-hub-1/uvlhub#68]
Description:
The following workflows must be fixed: test, c1, deployment_on_webhook, deployment_on_dockerhub

- test.yml: contemplate discord bot
- ci1.yml: when merge from another branch is detected and has no conflicts, is done; when merge has conflicts, creates PR instead; if there is another PR open, launches error
- deployment_on_webhook/dockerhub.yml: are not used, should be removed
- render.yml: only activates when test.yml is successful

Steps to reproduce
When a commit is done, the corresponding workflow are activated, and launches errors.

Expected result:
These should not launch any error

Current result:
Launch errors

Additional information (Optional): 
Intentionally blank

**Comment by isabelcan7** [comment]
Antonio no te rayes, mejor deja la ci y los workflows que son chungos
