### ISSUE TITLE
WI-1.3: Download all datasets

### ISSUE THREAD

**Issue by Migueel0** [salmorejo-hub-1/uvlhub#73]
Description: Download all’ button somewhere that downloads all datasets with all models and in all formats.

**Comment by isabelcan7** [comment]
Menos mal que has hecho el fakenodo, pq documentar las issues no xd

**Comment by Migueel0** [comment]
> Menos mal que has hecho el fakenodo, pq documentar las issues no xd

Lo siento isabel me esforzaré más

**Comment by Migueel0** [comment]
Issue completed in this commit [e3c59d5](https://github.com/salmorejo-hub-1/uvlhub/commit/e3c59d52deb413d794dd8a4c4142c515da4b6354)
