### ISSUE TITLE
WI-1.3.3: Create a button to download all datasets zip

### ISSUE THREAD

**Issue by Migueel0** [salmorejo-hub-1/uvlhub#80]
Description: Create a button in frontend to download the zip with all datasets

**Comment by isabelcan7** [comment]
Bua pedazo de descripcion Miguel, te lo has currado.
Pero tu no eras anti-frontend?

**Comment by Migueel0** [comment]
Issue closed in this commit: [ac40a2f](https://github.com/salmorejo-hub-1/uvlhub/commit/ac40a2f08879c3d5d17c3c9bc15dbf123d8387c9)
