### ISSUE TITLE
Write team diary document

### ISSUE THREAD

**Issue by DavidFuentelsazRodriguez** [salmorejo-hub-1/uvlhub#81]
**Description:**
Develop a project documentation wiki page based on the structure outlined in the [[Diario del Equipo](https://github.com/EGCETSII/Entregables/wiki/Diario-del-Equipo)](https://github.com/EGCETSII/Entregables/wiki/Diario-del-Equipo). The document should include the most important decisions taken by the team.

**Steps:**  

1. **Structure Creation:**  
   - Analyze the example provided in the link to understand the structure and required sections.  
   - Create a template for the documentation in the repository's wiki.  

2. **Content Writing:**  
   - Fill in the required sections with accurate and detailed information about the project

3. **Formatting and Styling:**  
   - Ensure the document is well-organized and follows a consistent style.  
   - Use headings, bullet points, tables, or diagrams where appropriate.  

4. **Collaboration and Review:**  
   - Share the draft with the team for feedback.  
   - Incorporate suggestions and finalize the content.  

5. **Publishing:**  
   - Upload the completed document to the wiki.  
   - Test the links, images, and overall accessibility.

**Comment by isabelcan7** [comment]
David ya había creado una issue para esto, gracias por ignorarme xd, [ya la he cerrado, da igual](https://github.com/salmorejo-hub-1/uvlhub/issues/61)
